spring:
  application:
    name: crud-user

  datasource:
    url: jdbc:mysql://localhost:3306/creude
    username: TaylorSz
    password: tos200689

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        format_sql: true
  
  threads:
    virtual:
      enabled: true

server:
  error:
    include-stacktrace: on-param